import Head from "next/head";
import avatar from "../public/bitmoji-avatar.png";
import Image from "next/image";
import manageHomepage from "../public/manage-homepage.jpg";

export default function Home() {
  return (
    <div className="dark">
      <Head>
        <title>Eric W. Developer Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">Eric's Portfolio</h1>
            <a className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
              href="#projects"              
            >
              Projects
            </a>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-6xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Eric W.
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Frontend Developer <br />
              (react.js, next.js, tailwindcss)
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Freelancer providing services in frontend development
            </p>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={avatar} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              My services include developing and maintaining websites.
              Below are some projects I have developed.
            </p>
          </div>
        </section>

        <section id='projects' className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Projects</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Below are projects that I have worked on.             
            </p>            
          </div>
          
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <Image
                src={manageHomepage}
                className="rounded-lg object-cover"
                width-200
                height-200
                layout="responsive"                
              />

              <p class='text-white text-1xl'>
                This is project from frontend mentor that I implemented in
                next.js and tailwindcss.                
              </p> 

              <a href='https://github.com/eric-waithaka/manage-site-landing-page' class='text-red-200 underline'>
                  Github repo
              </a>             
            </div>
                  
          </div>
        </section>
      </main>
    </div>
  );
}
